# This is a basic workflow to help you get started with Actions

name: Docker Image CI for GHCR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_and_publish"
  build_and_publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Build and publish docker image to ghcr.io
      - name: Build and pulish the image
        run: |
          docker login --username hat3ph --password ${{ secrets.GH_PAT }} ghcr.io
          docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v6,linux/arm/v7 . --tag ghcr.io/hat3ph/adguard-unbound:latest
          docker push ghcr.io/hat3ph/adguard-unbound:latest
